### ISSUE TITLE
css tweaks

### ISSUE THREAD

**Issue by umq** [onukura/gitbcket-swagger-plugin#8]
1. background color of version number is maskedy by built-in bootstrap (code.lass)
![image](https://user-images.githubusercontent.com/18342/85610692-2fb39480-b692-11ea-890d-00abd7905d85.png)
you might have clobber setting within [asset/style.css](https://github.com/onukura/gitbucket-swagger-plugin/blob/df9476ed202fe8cee2171baacec06d6dc82a3a85/src/main/resources/swagger/assets/style.css#L1)
I do not see `#js-openapi-viewer`, but `#swagger-viewer` instead.  Append or change selector; `#swagger-viewer pre.version` might work.

2. in `.wrapper` class, `skin-*` rule wins for `background-color`
![image](https://user-images.githubusercontent.com/18342/85611680-224ada00-b693-11ea-9b6d-e7a9eb64a90f.png)
setting a style like `#swagger-viewer .wrapper { background-color: transparent; }` might work.

**Comment by onukura** [comment]
@umq Thanks!
